import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Nav } from '@/components/Nav'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ao3 Muted CSS Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* this is where the title of the site will go */}
        <div className={styles.center}>
          <div className={styles.description}>
            <p>
              Some Title
            </p>
          </div>
        </div>
        {/* this is the site navigation; each one will be a different component */}
        <Nav/>
      </main>
    </>
  )
}
