import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Ao3 Muted CSS Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* this is where the title of the site will go */}
        <div className={styles.center}>
          <div className={styles.description}>
            <p>
              Some Title
            </p>
          </div>
        </div>
        {/* this is the site navigation; each one will be a different component */}
        <div className={styles.center}>
          <div className={styles.card}>
            <p className={styles.description}>
              Mute a Tag
            </p>
          </div>
          <div className={styles.card}>
            <p className={styles.description}>
              Mute a Fic
            </p>
          </div>
          <div className={styles.card}>
            <p className={styles.description}>
              How to Use
            </p>
          </div>
        </div>

        <div className={styles.center}>
          <p>this is where the thingy will go</p>
        </div>
      </main>
    </>
  )
}
